### ISSUE TITLE
Unable to find utils/colorize.js

### ISSUE THREAD

**Issue by doapp-jeremiah** [discoveryjs/jora-cli#4]
Installing jora-cli from npm only includes the bin/jora and index.js files.  Looks like the utils folder wasn't included in the files portion of the package.json

**Comment by lahmatiy** [comment]
Thank you for a bug report!
Fixing asap

**Comment by exdis** [comment]
Missed files now included to package.json#files section. Please update jora-cli to version [1.1.1](https://github.com/discoveryjs/jora-cli/releases/tag/v1.1.1)

**Comment by doapp-jeremiah** [comment]
Fixed it, working great now.  Thanks again!
